name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the client Docker image
      run: docker build -t matteorosani/office-queue-managment-client client
    - name: Push the client Docker image
      run: docker push matteorosani/office-queue-managment-client
    - name: Build the server Docker image
      run: docker build -t matteorosani/office-queue-managment-server server
    - name: Push the server Docker image
      run: docker push matteorosani/office-queue-managment-server
